ktor:
  application:
    modules:
      - com.anjo.ApplicationKt.module
  deployment:
    port: 8080
  redis:
    port: ${REDIS_PORT:6379}
    host: my-redis
    password: ${REDIS_PASSWORD:default}
    timeout: 10
    client-name: statistic-service
    ssl: false